#!bin/bash
total 36
drwxr-xr-x 2 root root 184 Mar  7 20:35 .
drwxr-xr-x 5 root root  91 Mar  7 18:48 ..
-rwxr-xr-x 1 root root  32 Mar  7 19:03 0-hello_world
-rwxr-xr-x 1 root root  28 Mar  7 19:36 1-confused_smiley
-rwxr-xr-x 1 root root  28 Mar  7 20:08 2-hellofile
-rwxr-xr-x 1 root root  39 Mar  7 20:12 3-twofiles
-rwxr-xr-x 1 root root  29 Mar  7 20:19 4-lastlines
-rwxr-xr-x 1 root root  34 Mar  7 20:17 5-firstlines
-rwxr-xr-x 1 root root  38 Mar  7 20:29 6-third_line
-rw-r--r-- 1 root root  11 Mar  7 20:35 8-cwd_state
-rw-r--r-- 1 root root  19 Mar  7 18:48 README.md
